### vll
POST http://localhost:8080/api/instruments/2
Accept: application/json
Content-Type: application/json

{
        
        "nom": "piano",
        "marque": "yamaha",
        "description": "painooo",
        "prixHorsTVA": 1000,
        "prixTVA": 1200,
        "quantiteEnStock": 10
        
        
        
       

        
}

### vll
POST http://localhost:8080/api/instruments/978cbbbb-4dba-46f3-8185-e8b1c17dbc25/images
Accept: application/json
Content-Type: application/json

{
    
    "url": "https://d1aeri3ty3izns.cloudfront.net/media/29/292337/1200/preview.jpg"
    
}

### vll
POST http://localhost:8080/api/clients
Accept: application/json
Content-Type: application/json

{
  "nom": "lounas",
  "email": "megane.nait@outlook.fr"
  
    
    
}


### vll
POST http://localhost:8080/api/lignesPanier/0a7426e0-f7d0-4a71-8493-eced9fcba643/658df6c2-b597-43b8-94ce-d440c499007e
Accept: application/json
Content-Type: application/json

{
    
    "quantite": 2
}